
// Objective-C API for talking to the following Go packages
//
//	github.com/blockcodemagic/filepathwalk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Filepathwalk_FRAMEWORK_H__
#define __Filepathwalk_FRAMEWORK_H__

#include "Filepathwalk.objc.h"
#include "Universe.objc.h"

#endif
