// Objective-C API for talking to github.com/blockcodemagic/filepathwalk Go package.
//   gobind -lang=objc github.com/blockcodemagic/filepathwalk
//
// File is generated by gobind. Do not edit.

#ifndef __Filepathwalk_H__
#define __Filepathwalk_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void FilepathwalkWalk(NSString* _Nullable rootPath);

#endif
